### ISSUE TITLE
pickle_db

### ISSUE THREAD

**Issue by georgebecerescu** [fyoorer/ShadowClone#12]
Hi, what can I put for Pickle_db or where can I find the bucket-hash.db?

python shadowclone.py -i /home/kali/range.txt --split 100 -o test.txt -c "/go/bin/httpx -l {INPUT}"
2022-10-11 23:07:27,214 [INFO] Splitting input file into chunks of 100 lines
2022-10-11 23:07:27,219 [INFO] Uploading chunks to storage
Traceback (most recent call last):
  File "/home/kali/Tools/ShadowClone/shadowclone.py", line 128, in <module>
    db.dump()  # save the db to file
  File "/usr/local/lib/python3.10/dist-packages/pickledb.py", line 92, in dump
    json.dump(self.db, open(self.loco, 'wt'))
FileNotFoundError: [Errno 2] No such file or directory: ''

in config.py I have the following line:

PICKLE_DB=""

FYI, it has same errors on running the RUN go install -... /nuclei@latest but I skipped nuclei installation.
Thank you!

**Comment by georgebecerescu** [comment]
Later edit: apparently you can put a path to any local file for it to write into
