### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by kepangada** [fyoorer/ShadowClone#17]
```
(env) root@zyz:~/ShadowClone# lithops runtime create recon --memory 512 --timeout 800
2022-12-06 00:33:19,115 [INFO] lithops.config -- Lithops v2.5.8
2022-12-06 00:33:19,115 [DEBUG] lithops.config -- Loading configuration from /root/.lithops/config
2022-12-06 00:33:19,133 [DEBUG] lithops.config -- Loading Serverless backend module: aws_lambda
2022-12-06 00:33:19,192 [DEBUG] lithops.config -- Loading Storage backend module: aws_s3
2022-12-06 00:33:19,193 [INFO] lithops.scripts.cli -- Creating new lithops runtime: recon
2022-12-06 00:33:19,193 [DEBUG] lithops.storage.backends.aws_s3.aws_s3 -- Creating S3 client
2022-12-06 00:33:19,290 [INFO] lithops.storage.backends.aws_s3.aws_s3 -- S3 client created - Region: ap-southeast-1
2022-12-06 00:33:19,290 [DEBUG] lithops.serverless.backends.aws_lambda.aws_lambda -- Creating AWS Lambda client
2022-12-06 00:33:19,290 [DEBUG] lithops.serverless.backends.aws_lambda.aws_lambda -- Creating Boto3 AWS Session and Lambda Client
2022-12-06 00:33:20,206 [INFO] lithops.serverless.backends.aws_lambda.aws_lambda -- AWS Lambda client created - Region: ap-southeast-1
2022-12-06 00:33:20,207 [DEBUG] lithops.serverless.backends.aws_lambda.aws_lambda -- Creating new Lithops lambda function: lithops_v2-5-8_gzmx_recon_512MB
Traceback (most recent call last):
  File "/root/ShadowClone/env/lib/python3.8/site-packages/lithops/serverless/backends/aws_lambda/aws_lambda.py", line 371, in create_runtime
    response = self.ecr_client.describe_images(repositoryName=repo_name)
  File "/root/ShadowClone/env/lib/python3.8/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/ShadowClone/env/lib/python3.8/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.RepositoryNotFoundException: An error occurred (RepositoryNotFoundException) when calling the DescribeImages operation: The repository with name 'lithops_v2-5-8_gzmx/recon' does not exist in the registry with id '866113468777'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ShadowClone/env/bin/lithops", line 8, in <module>
    sys.exit(lithops_cli())
  File "/root/ShadowClone/env/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/ShadowClone/env/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/ShadowClone/env/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/ShadowClone/env/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/ShadowClone/env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/ShadowClone/env/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/ShadowClone/env/lib/python3.8/site-packages/lithops/scripts/cli.py", line 434, in create
    runtime_meta = compute_handler.create_runtime(name, mem, timeout=to)
  File "/root/ShadowClone/env/lib/python3.8/site-packages/lithops/serverless/serverless.py", line 73, in create_runtime
    return self.backend.create_runtime(runtime_name, memory, timeout=timeout)
  File "/root/ShadowClone/env/lib/python3.8/site-packages/lithops/serverless/backends/aws_lambda/aws_lambda.py", line 376, in create_runtime
    raise Exception('Runtime {} is not deployed to ECR'.format(runtime_name))
Exception: Runtime recon is not deployed to ECR

```

I thought the problem was with the "role" but I have adjusted what you gave on the wiki and it still has an error

**Comment by kepangada** [comment]
fixed. you have to add iam passrole to policy
