### ISSUE TITLE
Rate limit trigger 

### ISSUE THREAD

**Issue by m3chboy** [fyoorer/ShadowClone#25]
Any way to fix rate limit error,

```
Exception: Error 429: {"Reason":"CallerRateLimitExceeded","Type":"User","message":"Rate exceeded"}
2023-05-02 07:02:53,124 [INFO] wait.py:97 -- ExecutorID 4c24f3-0 - Getting results from 231 function activations
exception calling callback for <Future at 0x7ff08c10a580 state=finished raised Exception>
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 330, in _invoke_callbacks
    callback(self)
  File "/root/ShadowClone/env/lib/python3.9/site-packages/lithops/invokers.py", line 435, in _callback
    future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/ShadowClone/env/lib/python3.9/site-packages/lithops/invokers.py", line 366, in _invoke_task
    activation_id = self.compute_handler.invoke(payload)
  File "/root/ShadowClone/env/lib/python3.9/site-packages/lithops/serverless/serverless.py", line 59, in invoke
    return self.backend.invoke(runtime_name, runtime_memory, job_payload)
  File "/root/ShadowClone/env/lib/python3.9/site-packages/lithops/serverless/backends/aws_lambda/aws_lambda.py", line 658, in invoke
    raise Exception('Error {}: {}'.format(r.status_code, r.text))
Exception: Error 429: {"Reason":"CallerRateLimitExceeded","Type":"User","message":"Rate exceeded"}
```

**Comment by sakyb7** [comment]
how do fix you fix this...?

**Comment by ed-red** [comment]
https://us-east-1.console.aws.amazon.com/servicequotas/home/services/lambda/quotas

Request increase Concurrent executions
