### ISSUE TITLE
Issue after running "lithops runtime deploy sc-runtime --memory 512 --timeout 300"

### ISSUE THREAD

**Issue by 0xlance** [fyoorer/ShadowClone#26]
2023-05-02 18:42:13,290 [DEBUG] aws_lambda.py:716 -- Extracting runtime metadata from: sc-runtime
Traceback (most recent call last):
  File "/home/ubuntu/arsenal/ShadowClone/env/bin/lithops", line 8, in <module>
    sys.exit(lithops_cli())
  File "/home/ubuntu/arsenal/ShadowClone/env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/arsenal/ShadowClone/env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/arsenal/ShadowClone/env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/arsenal/ShadowClone/env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/arsenal/ShadowClone/env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/arsenal/ShadowClone/env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/arsenal/ShadowClone/env/lib/python3.9/site-packages/lithops/scripts/cli.py", line 496, in deploy
    runtime_meta = compute_handler.deploy_runtime(runtime_name, runtime_memory, runtime_timeout)
  File "/home/ubuntu/arsenal/ShadowClone/env/lib/python3.9/site-packages/lithops/serverless/serverless.py", line 73, in deploy_runtime
    return self.backend.deploy_runtime(runtime_name, memory, timeout=timeout)
  File "/home/ubuntu/arsenal/ShadowClone/env/lib/python3.9/site-packages/lithops/serverless/backends/aws_lambda/aws_lambda.py", line 538, in deploy_runtime
    runtime_meta = self._generate_runtime_meta(runtime_name, memory)
  File "/home/ubuntu/arsenal/ShadowClone/env/lib/python3.9/site-packages/lithops/serverless/backends/aws_lambda/aws_lambda.py", line 730, in _generate_runtime_meta
    raise Exception('An error occurred: {}'.format(result))
Exception: An error occurred: {'errorType': 'Runtime.InvalidEntrypoint', 'errorMessage': 'RequestId: d71d7abf-1fa0-4509-a7ad-c83772585ae4 Error: fork/exec /usr/local/bin/python: exec format error'}

**Comment by abdilahrf** [comment]
Same issue, Have you resolved this @0xlance ?

**Comment by mk7120** [comment]
I got the same issue, did u guys resolve it?

**Comment by abdilahrf** [comment]
Use ubuntu, don't mac

**Comment by mk7120** [comment]
I used Ubuntu not mac
