### ISSUE TITLE
getting error while running this command lithops runtime build sc-runtime -f Dockerfile

### ISSUE THREAD

**Issue by falcon319** [fyoorer/ShadowClone#3]
2022-01-24 14:04:46,069 [INFO] lithops.config -- Lithops v2.5.8
2022-01-24 14:04:46,069 [DEBUG] lithops.config -- Loading configuration from /root/.lithops/config
2022-01-24 14:04:46,139 [DEBUG] lithops.config -- Loading Serverless backend module: aws_lambda
2022-01-24 14:04:46,240 [DEBUG] lithops.serverless.backends.aws_lambda.aws_lambda -- Creating AWS Lambda client
2022-01-24 14:04:46,240 [DEBUG] lithops.serverless.backends.aws_lambda.aws_lambda -- Creating Boto3 AWS Session and Lambda Client
2022-01-24 14:04:47,588 [INFO] lithops.serverless.backends.aws_lambda.aws_lambda -- AWS Lambda client created - Region: us-east-1
2022-01-24 14:04:47,589 [INFO] lithops.serverless.backends.aws_lambda.aws_lambda -- Going to create runtime -d for AWS Lambda
2022-01-24 14:04:47,590 [DEBUG] lithops.utils -- Creating function handler zip in lithops_lambda.zip
Traceback (most recent call last):
  File "/home/cherry/Desktop/ShadowClone/env/bin/lithops", line 8, in <module>
    sys.exit(lithops_cli())
  File "/home/cherry/Desktop/ShadowClone/env/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/cherry/Desktop/ShadowClone/env/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/cherry/Desktop/ShadowClone/env/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cherry/Desktop/ShadowClone/env/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cherry/Desktop/ShadowClone/env/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cherry/Desktop/ShadowClone/env/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/cherry/Desktop/ShadowClone/env/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cherry/Desktop/ShadowClone/env/lib/python3.8/site-packages/lithops/scripts/cli.py", line 465, in build
    compute_handler.build_runtime(name, file, ctx.args)
  File "/home/cherry/Desktop/ShadowClone/env/lib/python3.8/site-packages/lithops/serverless/serverless.py", line 66, in build_runtime
    self.backend.build_runtime(runtime_name, file, extra_args)
  File "/home/cherry/Desktop/ShadowClone/env/lib/python3.8/site-packages/lithops/serverless/backends/aws_lambda/aws_lambda.py", line 319, in build_runtime
    subprocess.check_call(cmd.split())
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'None'

**Comment by fyoorer** [comment]
are you running this command from the same directory where you have kept your Dockerfile? If not you can give it a path to your dockerfile like this 

`lithops runtime build sc-runtime -f /path/to/Dockerfile`

**Comment by melmel27** [comment]
python3 --version
Python 3.8.10

**Comment by georgebecerescu** [comment]
Hi, I have the same error...any hints to bypass it?
└─$ lithops runtime build sc-runtime -f Dockerfile
2022-10-11 20:09:44,211 [INFO] lithops.config -- Lithops v2.5.8
2022-10-11 20:09:44,211 [DEBUG] lithops.config -- Loading configuration from /home/kali/.lithops/config
2022-10-11 20:09:44,300 [DEBUG] lithops.config -- Loading Serverless backend module: aws_lambda
2022-10-11 20:09:45,006 [DEBUG] lithops.serverless.backends.aws_lambda.aws_lambda -- Creating AWS Lambda client
2022-10-11 20:09:45,006 [DEBUG] lithops.serverless.backends.aws_lambda.aws_lambda -- Creating Boto3 AWS Session and Lambda Client
2022-10-11 20:09:46,233 [INFO] lithops.serverless.backends.aws_lambda.aws_lambda -- AWS Lambda client created - Region: eu-central-1
2022-10-11 20:09:46,250 [INFO] lithops.serverless.backends.aws_lambda.aws_lambda -- Going to create runtime sc-runtime for AWS Lambda
2022-10-11 20:09:46,252 [DEBUG] lithops.utils -- Creating function handler zip in lithops_lambda.zip
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=sc-runtime&target=&ulimits=null&version=1": dial unix /var/run/docker.sock: connect: permission denied
Traceback (most recent call last):
  File "/usr/local/bin/lithops", line 8, in <module>
    sys.exit(lithops_cli())
  File "/home/kali/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/kali/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/kali/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kali/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kali/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kali/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/kali/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lithops/scripts/cli.py", line 465, in build
    compute_handler.build_runtime(name, file, ctx.args)
  File "/usr/local/lib/python3.10/dist-packages/lithops/serverless/serverless.py", line 66, in build_runtime
    self.backend.build_runtime(runtime_name, file, extra_args)
  File "/usr/local/lib/python3.10/dist-packages/lithops/serverless/backends/aws_lambda/aws_lambda.py", line 319, in build_runtime
    subprocess.check_call(cmd.split())
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/docker', 'build', '-t', 'sc-runtime', '-f', 'Dockerfile', '.']' returned non-zero exit status 1.

**Comment by georgebecerescu** [comment]
Thank you! It's working :)

**Comment by b1bek** [comment]
I am getting this error.

```bash
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/protocolinit
github.com/projectdiscovery/tlsx/pkg/tlsx
The command '/bin/sh -c go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest' returned a non-zero code: 2
Traceback (most recent call last):
  File "/root/ShadowClone/env/bin/lithops", line 8, in <module>
    sys.exit(lithops_cli())
  File "/root/ShadowClone/env/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/ShadowClone/env/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/ShadowClone/env/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/ShadowClone/env/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/ShadowClone/env/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/ShadowClone/env/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/ShadowClone/env/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/ShadowClone/env/lib/python3.10/site-packages/lithops/scripts/cli.py", line 465, in build
    compute_handler.build_runtime(name, file, ctx.args)
  File "/root/ShadowClone/env/lib/python3.10/site-packages/lithops/serverless/serverless.py", line 66, in build_runtime
    self.backend.build_runtime(runtime_name, file, extra_args)
  File "/root/ShadowClone/env/lib/python3.10/site-packages/lithops/serverless/backends/aws_lambda/aws_lambda.py", line 319, in build_runtime
    subprocess.check_call(cmd.split())
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/docker', 'build', '-t', 'sc-runtime', '-f', 'Dockerfile', '.']' returned non-zero exit status 2.
(env) ➜  ShadowClone git:(main) ✗ python --version
Python 3.10.6
```

**Comment by b1bek** [comment]
Solved above error by editing Dockerfile to copy binary. Python3.10 doesn't support lambda though.
```
COPY ./nuclei /usr/local/bin/nuclei
```
