### ISSUE TITLE
error when installing naabu

### ISSUE THREAD

**Issue by marcelo321** [fyoorer/ShadowClone#45]
I can't install naabu and I don't know what's missing:

```
 89 |     RUN apt-get install libpcap-dev -y
  90 | >>> RUN go get -v github.com/projectdiscovery/naabu/v2/cmd/naabu
  91 |     #RUN go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest > /tmp/naabu_install.log 2>&1
  92 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c go get -v github.com/projectdiscovery/naabu/v2/cmd/naabu" did not complete successfully: exit code: 1
Traceback (most recent call last):
  File "/usr/local/bin/lithops", line 8, in <module>
    sys.exit(lithops_cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lithops/scripts/cli.py", line 456, in build
    compute_handler.build_runtime(runtime_name, file, ctx.args)
  File "/usr/local/lib/python3.10/dist-packages/lithops/serverless/serverless.py", line 66, in build_runtime
    self.backend.build_runtime(runtime_name, file, extra_args)
  File "/usr/local/lib/python3.10/dist-packages/lithops/serverless/backends/aws_lambda/aws_lambda.py", line 354, in build_runtime
    utils.run_command(cmd)
  File "/usr/local/lib/python3.10/dist-packages/lithops/utils.py", line 713, in run_command
    sp.check_call(cmd.split())
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/docker', 'build', '-t', 'sc-runtime', '-f', 'Dockerfile', '.']' returned non-zero exit status 1.
2024-04-25 17:50:07,199 [INFO] config.py:134 -- Lithops v2.8.0
2024-04-25 17:50:07,200 [DEBUG] config.py:93 -- Loading configuration from /root/.lithops/config
```

**Comment by osamahamad** [comment]
for me, kind of the same error happens for subfinder. I'm trying figure out whats the problem

**Comment by osamahamad** [comment]
Check the error above, for me , this installed by simply updating Go version in the Dockerfile into the latest 

I think u should try changing go install lines to 

```
#RUN wget https://dl.google.com/go/go1.20.5.linux-amd64.tar.gz
RUN wget https://go.dev/dl/go1.22.3.linux-amd64.tar.gz
#RUN tar -xvf go1.20.5.linux-amd64.tar.gz
RUN tar -xvf go1.22.3.linux-amd64.tar.gz
#RUN rm go1.20.5.linux-amd64.tar.gz
RUN rm go1.22.3.linux-amd64.tar.gz
RUN mv go /usr/local

```
