### ISSUE TITLE
Function stuck in pending state

### ISSUE THREAD

**Issue by BlueCanary-DM** [fyoorer/ShadowClone#5]
It worked at the first go.

Then I've added some other tooling to the Dockerfile and used this command to rebuild the Docker:

```
lithops runtime build sc-runtime -f Dockerfile
```

Since then, I'm not able anymore to run the program. Even Lithops test fails me:

```
lithops test
2022-01-24 10:46:09,925 [INFO] lithops.config -- Lithops v2.5.8
2022-01-24 10:46:10,081 [INFO] lithops.storage.backends.aws_s3.aws_s3 -- S3 client created - Region: eu-west-3
2022-01-24 10:46:10,124 [INFO] lithops.serverless.backends.aws_lambda.aws_lambda -- AWS Lambda client created - Region: eu-west-3
2022-01-24 10:46:10,125 [INFO] lithops.invokers -- ExecutorID d5971d-0 | JobID A000 - Selected Runtime: python38 - 512MB
2022-01-24 10:46:10,218 [INFO] lithops.invokers -- Runtime python38 with 512MB is not yet installed
2022-01-24 10:46:10,311 [INFO] lithops.serverless.backends.aws_lambda.aws_lambda -- Creating default lambda layer for runtime python38
Traceback (most recent call last):
  File "/root/tools/ShadowClone/test/bin/lithops", line 8, in <module>
    sys.exit(lithops_cli())
  File "/root/tools/ShadowClone/test/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/tools/ShadowClone/test/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/tools/ShadowClone/test/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/tools/ShadowClone/test/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/tools/ShadowClone/test/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/tools/ShadowClone/test/lib/python3.8/site-packages/lithops/scripts/cli.py", line 168, in test_function
    fexec.call_async(hello, username)
  File "/root/tools/ShadowClone/test/lib/python3.8/site-packages/lithops/executors.py", line 205, in call_async
    runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
  File "/root/tools/ShadowClone/test/lib/python3.8/site-packages/lithops/invokers.py", line 121, in select_runtime
    runtime_meta = self.compute_handler.create_runtime(self.runtime_name, runtime_memory, runtime_timeout)
  File "/root/tools/ShadowClone/test/lib/python3.8/site-packages/lithops/serverless/serverless.py", line 73, in create_runtime
    return self.backend.create_runtime(runtime_name, memory, timeout=timeout)
  File "/root/tools/ShadowClone/test/lib/python3.8/site-packages/lithops/serverless/backends/aws_lambda/aws_lambda.py", line 413, in create_runtime
    layer_arn = self._create_layer(runtime_name)
  File "/root/tools/ShadowClone/test/lib/python3.8/site-packages/lithops/serverless/backends/aws_lambda/aws_lambda.py", line 200, in _create_layer
    response = self.lambda_client.invoke(
  File "/root/tools/ShadowClone/test/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/tools/ShadowClone/test/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the Invoke operation: The operation cannot be performed at this time. The function is currently in the following state: Pending
```

Already tried:
- Remove runtime reference in config.py
- Remove lambda function manually in console 
- Remove S3 bucket and create a new one and add new one in config 
- Changing AWS region

Would really appreciate some guidance in how to proceed when editing the Dockerfile

**Comment by falcon319** [comment]
do you encounter this error

Traceback (most recent call last):
  File "/usr/local/bin/lithops", line 8, in <module>
    sys.exit(lithops_cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lithops/scripts/cli.py", line 465, in build
    compute_handler.build_runtime(name, file, ctx.args)
  File "/usr/local/lib/python3.8/dist-packages/lithops/serverless/serverless.py", line 66, in build_runtime
    self.backend.build_runtime(runtime_name, file, extra_args)
  File "/usr/local/lib/python3.8/dist-packages/lithops/serverless/backends/aws_lambda/aws_lambda.py", line 319, in build_runtime
    subprocess.check_call(cmd.split())
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'None'

**Comment by BlueCanary-DM** [comment]
No, and please use your own issue :)

**Comment by vysecurity** [comment]
Where's the Dockerfile? I can't even see what you added.

**Comment by fyoorer** [comment]
After adding your tools you should run the `lithops runtime build ...` and `lithops runtime create ...` command again.
Also make sure you give a new name to the runtime  when running the command again like this:

`lithops runtime build sc-runtime1 -f Dockerfile`

`lithops runtime create sc-runtime1 --memory 512 --timeout 300`

Then update config.py with the new runtime name. This should solve it.
